config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'profile/show'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: 'tweets#index'
  resources :tweets, except: [:edit, :update] do
    resources :comments, only: [:create, :destroy] 
    member do
      post 'retweet'
    end 
  end
  resources :profiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :body, length: {maximum: 240}, allow_blank: false unless :tweet_id
  belongs_to :tweet, optional: true
  has_many :comments

def tweet_type
  if tweet_id? && body? 
     "quote_tweet"
  elsif tweet_id?
    "retweet"
  else
    "tweet"
  end
end

end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
  validates_uniqueness_of :username
  has_one_attached :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_reference
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  

  private

  def layout_by_reference
    if devise_controller?
      "devise"
    else
      "application"
    end
  end


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :profile_image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :profile_image])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    before_action :authenticate_user!
    before_action :set_tweet

    def create
       @comment = @tweet.comments.new(comment_params.merge(user: current_user))
       respond_to do |format|
        if @comment.save
            format.turbo_stream
        else
            format.html {redirect_to tweet_path(@tweet),
            alert: "Reply could not be created"}
        end
       end
    end
    def destroy
        @comment = @tweet.comments.find(params[:id])
        @comment.destroy
        respond_to do |format|
            format.turbo_stream
            format.html { redirect_to tweet_path(@tweet),
            notice: "Comment was deleted"}
        end
    end


    private

    def comment_params
        params.require(:comment).permit(:body)
    end

    def set_tweet
        @tweet = Tweet.find(params[:tweet_id])
    end
end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = User.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController 
  before_action :authenticate_user!
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
    respond_to do |format|
      if @tweet.save
        format.turbo_stream
      else
        format.html do
          flash[:tweet_errors] = @tweet.errors.full_messages
          redirect_to root_path
        end
      end    
    end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
  end
  
  def retweet
    @tweet = Tweet.find(params[:id])
    @retweet = current_user.tweets.new(tweet_id: @tweet.id)
    respond_to do |format|
      if @retweet.save
        format.turbo_stream
      else
        format.html { redirect_to fallback_location: @tweet, alert: 'Could not retweet' }
      end    
    end
  end
  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    # puts @tweet.comments
    @comments = @tweet.comments.order(created_at: :desc)
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, :tweet_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(flash_type)
    flash_base = "px-2 py-4 mx-auto font-sans font-medium text-center text-white"
    {
      notice: "bg-indigo-600 #{flash_base}",
      error:  "bg-red-600 #{flash_base}",
      alert: "bg-red-600 #{flash_base}"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def nav_classes
    ["devise/registrations", "devise/sessions", "devise/confirmations", "devise/passwords", "devise/unlocks"].include?(params[:controller]) ? "hidden" : nil
  end

  def label_class(options={})
    "block mb-1 font-normal leading-normal #{options[:extended_classes]}"
  end

  def input_class(options={})
    "rounded border border-gray-300 block w-full focus:outline-none focus:border-gray-400 outline-none focus-within:outline-none focus:ring-2 focus:ring-gray-200 #{options[:extended_classes]}"
  end

  def checkbox_class(options={})
    "rounded border-gray-300 border focus:ring-2 focus:ring-gray-200 text-blue-500 mr-1 #{options[:extended_classes]}"
  end

  def link_class(options={})
    "text-gray-700 underline hover:no-underline hover:text-gray-800 block #{options[:extended_classes]}"
  end

  def button_class(options={})
    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  def theme_button(theme)
    themes = {
      primary: "primary",
      secondary: "secondary",
      transparent: "transparent",
      dark: "dark"
    }

    case theme
    when themes[:primary]
      "bg-sky-500 hover:bg-sky-600 text-white"
    when themes[:secondary]
      "bg-teal-600 hover:bg-teal-700 text-white"
    when themes[:transparent]
      "bg-transparent hover:bg-gray-100 text-gray-700"
    when themes[:dark]
      "bg-gray-800 text-white shadow-sm hover:bg-gray-900"
    else
      "bg-white border border-gray-300 shadow-sm hover:bg-gray-100"
    end
  end

  def style_button(variant, theme)
    base = "rounded text-center font-sans font-normal outline-none leading-normal cursor-pointer transition ease-in-out duration-200 font-medium"

    case variant
    when "large"
      "px-5 py-4 text-lg #{base} #{theme}"
    when "small"
      "py-2 px-4 text-sm #{base} #{theme}"
    when "expanded"
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end
end


def profile_image(user, options={})
   size = case options[:size]
   when 'large'
    "w-20 h-20"
   when 'small'
    "w-10 h-10"
   else
    "w-14 h-14"
   end

   classes = "#{size} flex-shrink-0 rounded-full border-2 border-white"

   if user.profile_image.attached?
    image_tag user.profile_image, class: classes 
  else
    image_tag 'https://doodleipsum.com/700x700?bg=0ea5e9&i=f03db3af8c48f0bb74953ee80a098255', class: classes 
   end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class='p-4 border-b' id="<%= dom_id(comment) %>">
 <div class='flex space-x-3 items-start'>
   <%= profile_image(comment.user) %>
    <div class='flex-1'>
        <p class='font-bold'>
        <%= link_to comment.user.name, profile_path(comment.user), class:"hover:underline" %> 
        </p>
        <div class='prose prose-lg'><%= comment.body %></div>
    </div>
 </div>
 <ul class='-ml-3 flex space-x-14 items-start justify-center list-none'>
     <%
=begin%>
 <li> <%= link_to "comments #{tweet.comments.count ||= 0 }",tweet %></li> 
<%
=end%>
     <%
=begin%>
 <li><a href='#'>like</a></li> 
<%
=end%>
     <% if user_signed_in? && comment.user == current_user %>
        <li>
         <%= button_to "dlt", tweet_comment_path(comment.tweet, comment), method: :delete, form: { data: {turbo_confirm: 'Are you sure'}} %></li> 
     <% end %>
   </ul>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [tweet, @comment], data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |form| %>

   <div class='p-3'>
   <p class='pt-3'> 
      Replying to <%= link_to tweet.user.name, profile_path(tweet.user), class: 'text-sky-500' %>
   </p>
   <div class='flex items-start jutify-between space-x-3 py-6 border-b'>
      <%= profile_image(tweet.user) %>
      <div class='flex-1'>
        <%= form.label :body, class: 'sr-only' %>
        <%= form.text_area :body, class: 'border-none w-full resize-none rounded-md focus:shadow-none focus:border-none ring-0 focus:ring-0 focus:outline-none text-lg py-3 px-0 h-full min-h-[100px]', placeholder: 'Tweet your reply' %>
      </div>
      <%= form.submit "Reply",  class: 'px-6 py-2 bg-sky-400 text-white font-semibold rounded-full text-center cursor-pointer inline-block hover:bg-sky-600' %>
   </div>
   </div>
 
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend "#{dom_id(@tweet)}_comments" do %>
  <%= render "comment", comment: @comment %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove(@comment) %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white flex flex-col min-h-screen ">

    <header>
      <%= render "shared/flash_notice" %>
    </header>

    <main class="flex-grow container mx-auto px-4">
      <div class="grid lg:grid-cols-12 grid-cols-1 h-screen pr-6">
        <div class="lg:col-span-2 pt-6 pr-6">
          <%= link_to root_path, class:"link text-xl tracking-tight font-black" do %>
            <span class="text-sky-500">Tweeter</span>
          <% end %>
          <ul class="mt-6">
            <li>
              <%= link_to root_path, class: "rounded-full px-4 -ml-4 inline-flex items-center py-3 hover:bg-neutral-50 w-full text-lg transition ease-in-out duration-500" do %>
                <svg viewBox="0 0 24 24" aria-hidden="true" class="fill-current w-6 h-6 mr-4"><g><path d="M22.46 7.57L12.357 2.115c-.223-.12-.49-.12-.713 0L1.543 7.57c-.364.197-.5.652-.303 1.017.135.25.394.393.66.393.12 0 .243-.03.356-.09l.815-.44L4.7 19.963c.214 1.215 1.308 2.062 2.658 2.062h9.282c1.352 0 2.445-.848 2.663-2.087l1.626-11.49.818.442c.364.193.82.06 1.017-.304.196-.363.06-.818-.304-1.016zm-4.638 12.133c-.107.606-.703.822-1.18.822H7.36c-.48 0-1.075-.216-1.178-.798L4.48 7.69 12 3.628l7.522 4.06-1.7 12.015z"></path><path d="M8.22 12.184c0 2.084 1.695 3.78 3.78 3.78s3.78-1.696 3.78-3.78-1.695-3.78-3.78-3.78-3.78 1.696-3.78 3.78zm6.06 0c0 1.258-1.022 2.28-2.28 2.28s-2.28-1.022-2.28-2.28 1.022-2.28 2.28-2.28 2.28 1.022 2.28 2.28z"></path></g></svg>
                <span>Home</span>
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to profile_path(current_user), class: "rounded-full px-4 -ml-4 inline-flex items-center py-3 hover:bg-neutral-50 w-full text-lg transition ease-in-out duration-500" do %>
                  <svg class="fill-current w-6 h-6 mr-4"  viewBox="0 0 24 24" aria-hidden="true"><g><path d="M12 11.816c1.355 0 2.872-.15 3.84-1.256.814-.93 1.078-2.368.806-4.392-.38-2.825-2.117-4.512-4.646-4.512S7.734 3.343 7.354 6.17c-.272 2.022-.008 3.46.806 4.39.968 1.107 2.485 1.256 3.84 1.256zM8.84 6.368c.162-1.2.787-3.212 3.16-3.212s2.998 2.013 3.16 3.212c.207 1.55.057 2.627-.45 3.205-.455.52-1.266.743-2.71.743s-2.255-.223-2.71-.743c-.507-.578-.657-1.656-.45-3.205zm11.44 12.868c-.877-3.526-4.282-5.99-8.28-5.99s-7.403 2.464-8.28 5.99c-.172.692-.028 1.4.395 1.94.408.52 1.04.82 1.733.82h12.304c.693 0 1.325-.3 1.733-.82.424-.54.567-1.247.394-1.94zm-1.576 1.016c-.126.16-.316.246-.552.246H5.848c-.235 0-.426-.085-.552-.246-.137-.174-.18-.412-.12-.654.71-2.855 3.517-4.85 6.824-4.85s6.114 1.994 6.824 4.85c.06.242.017.48-.12.654z"></path></g></svg>
                  <span>Profile</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="lg:col-span-6 border-x">
          <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
        <div class="lg:col-span-4 pl-6 pt-6">
          <div class="bg-gray-50 w-full min-h-[150px] rounded-lg p-6 mb-6">Sidebar stuff</div>
          <% if user_signed_in? %>
            <p class="mb-4">
              Signed in as <%= current_user.name %>
            </p>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: button_class(theme: "primary"), data: { turbo: false } %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: button_class(theme: "primary") %>
          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-full antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white flex flex-col min-h-screen ">

    <header>
      <%= render "shared/flash_notice" %>
    </header>

    <main >
      
          <%= content_for?(:content) ? yield(:content) : yield %>
       
    </main>
  </body>
</html>

app/views/profiles/show.html.erb

<div class='p-6'>
  <div class='flex items-center justify-content-between space-x-4'>
     <div class='flex items-center'>
        <%= profile_image(@profile) %>
     </div>
     <div class='flex-1'>
      <div>
       <h2 class='font-bold text-3xl'> <%= @profile.name %> </h2>
       <%= "@" + @profile.name %>
      </div>
     </div>
    <div>
       <%= link_to "Edit profile", edit_user_registration_path, class: 'inline-flex justify-center items-center px-5 py-2 rounded-full border ring-4 focus:ring-sky-50 ring-transparent hover:ring-sky-50 hover:border-gray-300' %>
    </div>
  </div>
  <ul class='list-none divide-y -mx-6 mt-10'>
     <%= render collection: @profile.tweets, partial: 'tweets/tweet' %>
  </ul>
</div>

app/views/shared/_flash_notice.html.erb
<% unless flash['tweet_errors'] %>
  <% flash.each do |type, message| %>
    <div class="<%= flash_classes(type) %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "Kickoff Tailwind" %>
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "application", defer: true %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_navbar.html.erb
<nav class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto px-4 <%= nav_classes %>" data-controller="nav">
  <div class="flex items-center mr-6 flex-no-shrink">
    <%= link_to root_path, class:"link text-xl tracking-tight font-black" do %>
      <span class="sr-only">Add your app name here</span>
      <%# Remove this logo and add your own %>
      <svg fill="none" class="w-9 h-9" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="56" x2="463" y1="46" y2="465"><stop offset="0" stop-color="#8038ed"/><stop offset="1" stop-color="#3a0092"/></linearGradient><path d="m0 0h512v512h-512z" fill="#fff"/><rect fill="url(#a)" height="512" rx="110" width="512"/><g stroke="#fff"><circle cx="190" cy="302" r="79.5" stroke-opacity=".9" stroke-width="25"/><circle cx="254" cy="377" r="34" stroke-opacity=".8" stroke-width="10"/><circle cx="282" cy="227" r="106" stroke-width="50"/></g></svg>
    <% end %>
  </div>
  <div class="block lg:hidden">
    <%# Mobile nav toggle %>
    <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" data-action="click->nav#toggleMenu touch->nav#toggleMenu">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
  </div>
  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
    <div class="lg:flex-grow">
      <%= link_to "Basic Link", "#", class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
    </div>
    <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
      <div><%# More links can go here %></div>
      <% if user_signed_in? %>
        <%= link_to "Edit account", edit_user_registration_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= link_to "Sign up", new_user_registration_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:ml-2" %>

        <span class="h-5 w-px bg-gray-200 mx-3"></span>

        <%= link_to "https://github.com/justalever/kickoff_tailwind", target: :_blank, class: "group lg:ml-2 flex justify-center" do %>
          <svg class="fill-current text-gray-400 group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/tweets/_controls.html.erb
<ul class='-ml-3 flex space-x-14 items-start justify-start list-none'>
     <li> <%= link_to "comments #{tweet.comments.count ||= 0 }",tweet %></li>
     <li><a href='#'>like</a></li>
     <% if user_signed_in? && tweet.user == current_user %>
        <li>
         <%= button_to "dlt", tweet_path(tweet), method: :delete, form: { data: {turbo_confirm: 'Are you sure'}} %>
    <% else %>         
        <li><%= button_to "retweet 3", retweet_tweet_path(tweet), method: :post %></li>
     <% end %>
   </ul>

app/views/tweets/_empty.html.erb
<% unless Tweet.all.exists? %>
   <p>Nothing to see herer</p>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with model: @tweet, data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} do |form| %>
   <% if flash['tweet_errors'] %>
     <div class='bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3 mx-3'>
        <ul>
          <% flash['tweet_errors'].each do |error| %>
             <li> <%= error %> </li>
          <% end %>
        </ul>
     </div> 
   <% end %>

   <%= form.text_area :body, class: 'border-b border-t-0 border-x-0 mb-6 px-6 pt-6 block w-full border-gray-200 focus:shadow-none focus:outline-none focus:ring-transparent focus:border-gray-300 resize-none min-h-[180px] text-lg', placeholder: "What's on your mind" %>

   <div class='flex justify-end px-6 -mt-20'>
     <%= form.submit "Tweet", class: 'px-3 py-2 bg-sky-400 text-white font-semibold rounded-full text-center cursor-pointer inline-block hover:bg-sky-500 duration-300' %>
   </div>

<% end %>

app/views/tweets/_retweet.html.erb
<div class='px-6 py-3' id="<%= dom_id(tweet) %>">
<div>
  Retweeted by <%= "@" + tweet.user.username %>
</div>
   <div class='flex space-x-3 items-start pb-3'>
      <%= profile_image(tweet.user) %>
   </div>
   <div class='flex-1'>
     <p class='font-bold'> <%= link_to tweet.user.name, profile_path(tweet.user), class: 'hover:underline' %> </p>     
   </div>
   <div class='prose prose-lg'><%= tweet.body %></div>


   <%= render "tweets/controls", tweet: tweet %>


</div>


app/views/tweets/_tweet.html.erb
<div class='px-6 py-3' id="<%= dom_id(tweet) %>">
   <div class='flex space-x-3 items-start pb-3'>
      <%= profile_image(tweet.user) %>
   </div>
   <div class='flex-1'>
     <p class='font-bold'> <%= link_to tweet.user.name, profile_path(tweet.user), class: 'hover:underline' %> </p>     
   </div>
   <%= link_to tweet do %>
      <div class='prose prose-lg'><%= tweet.body %></div>
   <% end %>


   <%= render "tweets/controls", tweet: tweet %>





</div>


app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend "tweets" do %>
  <%= render "tweet", tweet: @tweet %>
<% end %>
<%= turbo_stream.update "empty" do %>
  <%= render "empty" %>
<% end %>

app/views/tweets/destroy.turbo_stream.erb
<%= turbo_stream.remove @tweet %>
<%= turbo_stream.update "empty" do %>
  <%= render "empty" %>
<% end %>
 

app/views/tweets/index.html.erb
<div class='mb-8'>
    <%= render "form" %>
</div>

<%= turbo_frame_tag 'tweets', class: 'divide-y' do %>
   <% @tweets.each do |tweet| %>
    <% puts tweet.tweet_type.parameterize %>
        <%= render "tweets/#{tweet.tweet_type.parameterize}", tweet: tweet %>
    <% end %>
<% end %>

<%= turbo_frame_tag "empty" do %>
  <% if @tweets.none? %>
    <%= render "empty" %>
  <% end %>
<% end %>

app/views/tweets/retweet.turbo_stream.erb
<%= turbo_stream.prepend "tweets" do %>
 <%= puts 'hello' %>
  <%= render "retweet", tweet: @retweet %>
<% end %>

app/views/tweets/show.html.erb
<%= render "tweets/#{@tweet.tweet_type.parameterize}", tweet: @tweet %>
<hr>
<div class='p-3 space-x-6 flex'>
 <p>
    <%= "1 retweet" %>
 </p>
 <p>
    <%= "1 likes" %>
 </p>
</div>
<hr>


<% if user_signed_in? %>
  <%= turbo_frame_tag "#{dom_id(@tweet)}_comment_form" do %>
        <%= render  "comments/form", tweet: @tweet %>
  <% end %>
<% else %>
  <p class='mt-6 text-center text-lg'>
     <%= link_to  "Sign in", new_user_session_path, class: 'text-sky-500 hover:text-sky-600 font-medium' %>
  </p>
<% end %>

<%= turbo_frame_tag "#{dom_id(@tweet)}_comments" do %>
 <% @comments.each do |comment| %>
    <%= render "comments/comment", comment: comment %>
 <% end %>
<% end %>